title: Insights Data Schemas
description: Insights Data Schemas
baseurl: "/service"
url: "https://road-core.github.io"

heading_anchors: true
search_enabled: true

aux_links:
  "Github repository":
    - "https://github.com/road-core/service/"

footer_content: "Copyright &copy; 2024, 2025 Red Hat and external authors"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - sources.tmpl.md

theme: jekyll-theme-leap-day
