name: Integration tests

on:
  - push
  - pull_request

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python version
        run: python --version
      - name: PDM installation
        run: pip install --user pdm
      - name: Install dependencies
        run: pdm install
      - name: Install devel dependencies
        run: pdm install --dev
      - name: Run integration tests
        run: pdm run python -m pytest -m 'not redis' tests/integration --cov=ols --cov=runner --cov-report term-missing
