name: Integration tests

on: [push, pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PDM installation
        run: pip install --user pdm
      - name: Install dependencies
        run: pdm install
      - name: Install devel dependencies
        run: pdm install --dev
      - name: Run integration tests
        run: pdm run python -m pytest -m 'not redis' tests/integration --cov=ols --cov=runner --cov-report term-missing
