name: Python linter

on:
  - push
  - pull_request

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python linter installation
        run: pip install --user pylint
      - name: Python linter
        run: pylint ols/
