name: Pyright

on:
  #- push
  #- pull_request

jobs:
  pyright:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: "Pyright"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311
