name: Shell check

on:
  - push
  - pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Shell check
        run: make shellcheck
